#!/bin/bash

# Use manifest-tool to create the manifest, given the experimental
# "docker manifest" command isn't available yet on Docker Hub.

curl -Lo manifest-tool https://github.com/estesp/manifest-tool/releases/download/v0.9.0/manifest-tool-linux-amd64
chmod +x manifest-tool

VERSION1="${IMAGE_NAME%-*}"
VERSION="${VERSION1#*/}"


if ./manifest-tool inspect "${VERSION}-amd64"; then
  if ./manifest-tool inspect "${VERSION}-i386"; then
    if ./manifest-tool inspect "${VERSION}-armv7"; then
      if ./manifest-tool inspect "${VERSION}-aarch64"; then
        sed -i -e "s|danmed/tasmobackupv1:latest|${VERSION}|" multi-arch-manifest.yaml
        ./manifest-tool push from-spec multi-arch-manifest.yaml
      fi
    fi
  fi
fi

exit 0
